### ISSUE TITLE
Node crashes on ECONNRESET

### ISSUE THREAD

**Issue by DeanCording** [iobroker-community-adapters/castv2-player#4]
I get the following crash in my application:

```
25 Jan 23:10:29 - [info] [google-cast:Central] Central speaker - Detached player
26 Jan 02:42:51 - [warn] [google-cast:Central] Central speaker - Client error: Error: Device timeout
    at fn.ontimeout (/data/data/projects/node-red/node-red-contrib-google-cast/node_modules/castv2-client/lib/senders/platform.js:56:26)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at fn.emit (events.js:208:7)
    at Timeout.ontimeout [as _onTimeout] (/data/data/projects/node-red/node-red-contrib-google-cast/node_modules/castv2-client/lib/controllers/heartbeat.js:44:10)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
26 Jan 02:42:51 - [info] [google-cast:Central] Central speaker - client disconnected
26 Jan 02:42:51 - [warn] [google-cast:Central] Central speaker - Client error: Error: Device timeout
    at fn.ontimeout (/data/data/projects/node-red/node-red-contrib-google-cast/node_modules/castv2-client/lib/senders/platform.js:56:26)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at fn.emit (events.js:208:7)
    at Timeout.ontimeout [as _onTimeout] (/data/data/projects/node-red/node-red-contrib-google-cast/node_modules/castv2-client/lib/controllers/heartbeat.js:44:10)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
26 Jan 02:42:51 - [warn] [google-cast:Central] Central speaker - Client error: Error: Device timeout
    at fn.ontimeout (/data/data/projects/node-red/node-red-contrib-google-cast/node_modules/castv2-client/lib/senders/platform.js:56:26)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at fn.emit (events.js:208:7)
    at Timeout.ontimeout [as _onTimeout] (/data/data/projects/node-red/node-red-contrib-google-cast/node_modules/castv2-client/lib/controllers/heartbeat.js:44:10)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
26 Jan 02:42:51 - [warn] [google-cast:Central] Central speaker - Client error: Error: Device timeout
    at fn.ontimeout (/data/data/projects/node-red/node-red-contrib-google-cast/node_modules/castv2-client/lib/senders/platform.js:56:26)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at fn.emit (events.js:208:7)
    at Timeout.ontimeout [as _onTimeout] (/data/data/projects/node-red/node-red-contrib-google-cast/node_modules/castv2-client/lib/controllers/heartbeat.js:44:10)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
26 Jan 02:42:58 - [warn] [google-cast:Central] Central speaker - Client error: Error: connect ECONNREFUSED 192.168.1.15:8009
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
26 Jan 02:42:58 - [warn] [google-cast:Central] Central speaker - Client error: Error: connect ECONNREFUSED 192.168.1.15:8009
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
26 Jan 02:42:58 - [warn] [google-cast:Central] Central speaker - Client error: Error: connect ECONNREFUSED 192.168.1.15:8009
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
26 Jan 02:42:58 - [warn] [google-cast:Central] Central speaker - Client error: Error: connect ECONNREFUSED 192.168.1.15:8009
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
26 Jan 02:42:59 - [warn] [google-cast:Central] Central speaker - Client error: Error: connect ECONNREFUSED 192.168.1.15:8009
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
26 Jan 02:42:59 - [warn] [google-cast:Central] Central speaker - Client error: Error: connect ECONNREFUSED 192.168.1.15:8009
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
26 Jan 02:42:59 - [warn] [google-cast:Central] Central speaker - Client error: Error: connect ECONNREFUSED 192.168.1.15:8009
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
26 Jan 02:42:59 - [warn] [google-cast:Central] Central speaker - Client error: Error: connect ECONNREFUSED 192.168.1.15:8009
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
26 Jan 02:43:01 - [warn] [google-cast:Central] Central speaker - Client error: Error: connect ECONNREFUSED 192.168.1.15:8009
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
26 Jan 02:43:01 - [warn] [google-cast:Central] Central speaker - Client error: Error: connect ECONNREFUSED 192.168.1.15:8009
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
26 Jan 02:43:01 - [warn] [google-cast:Central] Central speaker - Client error: Error: connect ECONNREFUSED 192.168.1.15:8009
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
26 Jan 02:43:01 - [warn] [google-cast:Central] Central speaker - Client error: Error: connect ECONNREFUSED 192.168.1.15:8009
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
26 Jan 02:43:02 - [red] Uncaught Exception:
26 Jan 02:43:02 - Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:615:25)
```

It looks like the exception is slipping through the cracks in _connectClient in persistentClient.js

**Comment by angelnu** [comment]
I added code to read error handlers to prevent that a DUP error might not get caught.

**Comment by angelnu** [comment]
uhm, I am not by any means a node.js expert so I have not any alternative, sorry.
